const restaurantList = [
    {
        data: {
            type: "F",
            id: "559535",
            name: "Chinese Hub",
            uuid: "cb2f92c0-3f1b-42a7-8a1e-f2b656747d73",
            city: "13",
            area: "Kakkanad",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "ydwiyhxzno5rwbynoik3",
            cuisines: ["Chinese", "South Indian", "Juices"],
            tags: [],
            costForTwo: 900,
            costForTwoString: "₹9 FOR TWO",
            deliveryTime: 39,
            minDeliveryTime: 39,
            maxDeliveryTime: 39,
            slaString: "39 MINS",
            lastMileTravel: 7,
            slugs: {
                restaurant: "chinese-hub-kakkanad-kakkanad",
                city: "kochi",
            },
            cityState: "13",
            address: "Palachuvad thrikkakara kakkanad kochi",
            locality: "Palachuvad",
            parentId: 16394,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 6300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 6300,
                message: "",
                title: "Delivery Charge",
                amount: "6300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "7 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "559535",
                deliveryTime: 39,
                minDeliveryTime: 39,
                maxDeliveryTime: 39,
                lastMileTravel: 7,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 100,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "638265",
            name: "Popsy - House Of Popsicles",
            uuid: "a7b2fbc3-1401-4c8c-944d-aceff16df831",
            city: "13",
            area: "Panampilly Nagar",
            totalRatingsString: "20+ ratings",
            cloudinaryImageId: "snzo23qx710kwbl6y7z5",
            cuisines: ["Indian"],
            tags: [],
            costForTwo: 4000,
            costForTwoString: "₹40 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "popsy---house-of-popsicles-panampilly-nagar-panampilly-nagar",
                city: "kochi",
            },
            cityState: "13",
            address:
                "56/2611 A, Panampilly Main Road,  Panampilly Nagar Ave, Thrikkakara Circle,  Ernakulam, Kerala - 682036",
            locality: "Panampilly Main Road",
            parentId: 385293,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3600,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3600,
                message: "",
                title: "Delivery Charge",
                amount: "3600",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            sla: {
                restaurantId: "638265",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 20,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "569597",
            name: "Clinjo Chayakaday",
            uuid: "0338aa48-9a87-4e02-bb92-758d29d205b7",
            city: "13",
            area: "Kaloor",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "yronk59n62istg24czyl",
            cuisines: ["Juices", "Beverages"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            slaString: "30 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "clinjo-chayakaday-kaloor-kaloor",
                city: "kochi",
            },
            cityState: "13",
            address:
                "CLINJO CHAYAKADAY,PIPE LANE ROAD,KATHRIKADAVU,KALOOR,THRIKKAKARA CIRCLE,ERNAKULAM,KERALA-682017",
            locality: "Thrikkakara",
            parentId: 342061,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3600,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3600,
                message: "",
                title: "Delivery Charge",
                amount: "3600",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "569597",
                deliveryTime: 30,
                minDeliveryTime: 30,
                maxDeliveryTime: 30,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "629639",
            name: "Sundae Everyday Ice Creams",
            uuid: "dc6043be-f99b-450d-a65d-582601f3aab4",
            city: "13",
            area: "Panampilly Nagar",
            totalRatingsString: "20+ ratings",
            cloudinaryImageId: "tdxnegu3i2pvyg28sa30",
            cuisines: ["Beverages", "Ice Cream", "Desserts"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            slaString: "28 MINS",
            lastMileTravel: 3.5,
            slugs: {
                restaurant: "sundae-everyday-ice-creams-panampilly-nagar-panampilly-nagar",
                city: "kochi",
            },
            cityState: "13",
            address:
                "Door No.56/2718,Plot No. 824, Panampilly Nagar, Eranakulam Circle, Ernakulam, Kerala, 682036",
            locality: "Eranakulam Circle",
            parentId: 20021,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3600,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3600,
                message: "",
                title: "Delivery Charge",
                amount: "3600",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3.5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "629639",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 3.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 20,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "124246",
            name: "Choco Brown",
            uuid: "e36bc75c-10b7-4bd0-bc32-d706f3cd42a9",
            city: "13",
            area: "Elamkulam",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "iqwixybs4qa2efiqbzet",
            cuisines: ["Desserts"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 5,
            slugs: {
                restaurant: "choco-brown-vennala-vyttila",
                city: "kochi",
            },
            cityState: "13",
            address:
                "Door No. 33/461 AB, B1, B2, Arakkakadavu Road, Kochi, Arakkakadavu, Vennala, Ernakulam, Kerala 682028",
            locality: "Arakkakadavu",
            parentId: 62301,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 5300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 5300,
                message: "",
                title: "Delivery Charge",
                amount: "5300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "5 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹40",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "124246",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.7",
            totalRatings: 100,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "714596",
            name: "Daily Meet",
            uuid: "dfdad428-38a7-405a-92df-198312b0e65e",
            city: "13",
            area: "Panampilly Nagar",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "5cb1a025942fd8b5ddb7ad7a417b3504",
            cuisines: ["Beverages"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 37,
            minDeliveryTime: 37,
            maxDeliveryTime: 37,
            slaString: "37 MINS",
            lastMileTravel: 6.199999809265137,
            slugs: {
                restaurant: "daily-meet-panampilly-nagar-panampilly-nagar",
                city: "kochi",
            },
            cityState: "13",
            address:
                "DAILY MEET/ 54/2746, NEAR SH COLLEGE,  MATTUMMEL, THEVARA, Eranakulam  Circle, Ernakulam, Kerala - 682013",
            locality: "Mattummel",
            parentId: 317592,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 5800,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 5800,
                message: "",
                title: "Delivery Charge",
                amount: "5800",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "6.1 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "714596",
                deliveryTime: 37,
                minDeliveryTime: 37,
                maxDeliveryTime: 37,
                lastMileTravel: 6.199999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: true,
        },
    },
    {
        data: {
            type: "F",
            id: "550469",
            name: "Nandanam Pure Veg Restaurant",
            uuid: "8a278025-8902-475b-bba3-a1543bbd2164",
            city: "13",
            area: "Tripunithura",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "do56xm3eisl2us2cf7hy",
            cuisines: ["South Indian", "Biryani", "Beverages", "Chinese"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            slaString: "31 MINS",
            lastMileTravel: 7.800000190734863,
            slugs: {
                restaurant: "nandanam-pure-veg-restaurant-thrippunithura-thrippunithura",
                city: "kochi",
            },
            cityState: "13",
            address:
                "JOSE C MATHEW., NANDANAM PURE VEG  RESTAURANT, 11/301, Vilakku Junction,  Irumpanam, Tripunithura, Piravam Circle,  Ernakulam, Kerala-682309",
            locality: "Vilakku Junction",
            parentId: 330790,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 6300,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 6300,
                message: "",
                title: "Delivery Charge",
                amount: "6300",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "7.8 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "₹100 OFF",
                subHeader: "ABOVE ₹399",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "550469",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 7.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 500,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "115968",
            name: "Juice Makkani",
            uuid: "459349d7-3205-4e80-aed1-1c82ebbc89fd",
            city: "13",
            area: "Edappally",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "z4jiwbfrpqad52ztoalu",
            cuisines: ["Ice Cream", "Juices", "Beverages"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 46,
            minDeliveryTime: 46,
            maxDeliveryTime: 46,
            slaString: "46 MINS",
            lastMileTravel: 8.300000190734863,
            slugs: {
                restaurant: "juice-makkani-edapally-edapally",
                city: "kochi",
            },
            cityState: "13",
            address: "VP Marakkar Rd, Edappally Toll",
            locality: "VP Marakkar Road",
            parentId: 20582,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 7800,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 7800,
                message: "",
                title: "Delivery Charge",
                amount: "7800",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "8.3 kms",
            hasSurge: false,
            sla: {
                restaurantId: "115968",
                deliveryTime: 46,
                minDeliveryTime: 46,
                maxDeliveryTime: 46,
                lastMileTravel: 8.300000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 1000,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "303869",
            name: "Maggie point",
            uuid: "6e3a5c75-d1c8-4b71-be0f-f6669f1f0bd6",
            city: "13",
            area: "Edappally",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "jsmh7etf5gsuneawe25f",
            cuisines: ["Chaat", "Snacks", "Beverages"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            slaString: "38 MINS",
            lastMileTravel: 8.800000190734863,
            slugs: {
                restaurant: "maggie-point-edapally-edapally",
                city: "kochi",
            },
            cityState: "13",
            address:
                "PWRA-40, 1st floor Ponekkara Rd, Ponekkara, Edappally, Kochi, Kerala 682041, India",
            locality: "Ponekkara",
            parentId: 129251,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 7800,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 7800,
                message: "",
                title: "Delivery Charge",
                amount: "7800",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "8.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "303869",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                lastMileTravel: 8.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 500,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "111120",
            name: "Udupi Vasant Mahal Hotel- Pure Veg",
            uuid: "843fddae-2973-470d-9766-5da6133c1b77",
            city: "13",
            area: "Thopumpady",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "lgp3otriwrcpptriaeba",
            cuisines: ["South Indian"],
            tags: [],
            costForTwo: 10000,
            costForTwoString: "₹100 FOR TWO",
            deliveryTime: 46,
            minDeliveryTime: 46,
            maxDeliveryTime: 46,
            slaString: "46 MINS",
            lastMileTravel: 9,
            slugs: {
                restaurant: "udupi-vasant-mahal-hotel-fort-kochi-fort-kochi",
                city: "kochi",
            },
            cityState: "13",
            address: "Thoppumpady ,Cochin- 682005",
            locality: "Aroor - Thoppumpady Road",
            parentId: 219082,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 7800,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 7800,
                message: "",
                title: "Delivery Charge",
                amount: "7800",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 1,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "9 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "111120",
                deliveryTime: 46,
                minDeliveryTime: 46,
                maxDeliveryTime: 46,
                lastMileTravel: 9,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.2",
            totalRatings: 500,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "630177",
            name: "Luv Cut Let",
            uuid: "40fedf60-1e34-40d3-9a59-e369569ad961",
            city: "13",
            area: "Kaloor",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "cb60e20470c4ab62426f4c583a6e4164",
            cuisines: ["Indian"],
            tags: [],
            costForTwo: 11400,
            costForTwoString: "₹114 FOR TWO",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            slaString: "27 MINS",
            lastMileTravel: 4.699999809265137,
            slugs: {
                restaurant: "luv-cut-let-kaloor-kaloor",
                city: "kochi",
            },
            cityState: "13",
            address:
                "G-1104, Stadium Round, Jawaharlal Nehru International Stadium, Kaloor, Kochi, Kerala 682017, India",
            locality: "Ernakulam",
            parentId: 326884,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4100,
                message: "",
                title: "Delivery Charge",
                amount: "4100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4.6 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "630177",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 4.699999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.6",
            totalRatings: 100,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "541441",
            name: "Parti Pastries",
            uuid: "365e6341-be98-4c17-854c-06efbfd7f10a",
            city: "13",
            area: "Elamkulam",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "hwmeijiwxzixmcxt3piz",
            cuisines: ["Bakery"],
            tags: [],
            costForTwo: 12000,
            costForTwoString: "₹120 FOR TWO",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            slaString: "23 MINS",
            lastMileTravel: 2,
            slugs: {
                restaurant: "parti-pastries-panampilly-nagar-panampilly-nagar-2",
                city: "kochi",
            },
            cityState: "13",
            address: "63/219 B, Ground Floor, Kaloor Kadavanthra Road, Elamkulam, Kochi",
            locality: "Kadavanthra Road",
            parentId: 307862,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3100,
                message: "",
                title: "Delivery Charge",
                amount: "3100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "60% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "541441",
                deliveryTime: 23,
                minDeliveryTime: 23,
                maxDeliveryTime: 23,
                lastMileTravel: 2,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "376052",
            name: "NIC Ice Creams",
            uuid: "baa984bd-6648-43d1-849d-3df3cd722126",
            city: "13",
            area: "Panampilly Nagar",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "d461cb7eac503656a2b4bb13e7c60b97",
            cuisines: ["Ice Cream", "Desserts"],
            tags: [],
            costForTwo: 12000,
            costForTwoString: "₹120 FOR TWO",
            deliveryTime: 20,
            minDeliveryTime: 20,
            maxDeliveryTime: 20,
            slaString: "20 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "nic-natural-ice-creams-parambithara-road-panampilly-nagar",
                city: "kochi",
            },
            cityState: "13",
            address:
                "Shop no 55/63-B (South-West Portion) Parambithara Road, Panampilly Nagar, Cochin, Kerala-682036, Ernakulam, Kerala-682036",
            locality: "Parambithara Road",
            parentId: 6249,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3600,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3600,
                message: "",
                title: "Delivery Charge",
                amount: "3600",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "376052",
                deliveryTime: 20,
                minDeliveryTime: 20,
                maxDeliveryTime: 20,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.6",
            totalRatings: 1000,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "379730",
            name: "Grameen Kulfi",
            uuid: "67834abc-1140-4e27-8990-e852dc2b63bb",
            city: "13",
            area: "Panampilly Nagar",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "hlxeqq2wy1xiqnfcyddb",
            cuisines: ["Ice Cream", "Desserts"],
            tags: [],
            costForTwo: 12000,
            costForTwoString: "₹120 FOR TWO",
            deliveryTime: 21,
            minDeliveryTime: 21,
            maxDeliveryTime: 21,
            slaString: "21 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "grameen-kulfi-parambithara-road-panampilly-nagar",
                city: "kochi",
            },
            cityState: "13",
            address:
                "Shop no 55/63-B (South-West Portion) Parambithara Road, Panampilly Nagar, Cochin, Kerala-682036, Ernakulam, Kerala-682036",
            locality: "Parambithara Road",
            parentId: 12175,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 3600,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 3600,
                message: "",
                title: "Delivery Charge",
                amount: "3600",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
            },
            sla: {
                restaurantId: "379730",
                deliveryTime: 21,
                minDeliveryTime: 21,
                maxDeliveryTime: 21,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.7",
            totalRatings: 500,
            new: false,
        },
    },
    {
        data: {
            type: "F",
            id: "603543",
            name: "Cold Craves",
            uuid: "181b335b-b320-4f1a-a0c7-c2138177d715",
            city: "13",
            area: "Kaloor",
            totalRatingsString: "Too Few Ratings",
            cloudinaryImageId: "dgpyivwiuxbyl9zdsmxq",
            cuisines: ["Ice Cream", "Beverages", "Desserts"],
            tags: [],
            costForTwo: 12000,
            costForTwoString: "₹120 FOR TWO",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            slaString: "34 MINS",
            lastMileTravel: 4.900000095367432,
            slugs: {
                restaurant: "cold-craves-kaloor-kaloor",
                city: "kochi",
            },
            cityState: "13",
            address: "Puthiya Road Junction, Kaloor, Kochi, Kerala 682017, India",
            locality: "Puthiya Road",
            parentId: 359323,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            chain: [],
            feeDetails: {
                fees: [
                    {
                        name: "distance",
                        fee: 4100,
                        message: "",
                    },
                    {
                        name: "time",
                        fee: 0,
                        message: "",
                    },
                    {
                        name: "special",
                        fee: 0,
                        message: "",
                    },
                ],
                totalFees: 4100,
                message: "",
                title: "Delivery Charge",
                amount: "4100",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "4.9 kms",
            hasSurge: false,
            sla: {
                restaurantId: "603543",
                deliveryTime: 34,
                minDeliveryTime: 34,
                maxDeliveryTime: 34,
                lastMileTravel: 4.900000095367432,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "--",
            totalRatings: 0,
            new: false,
        },
    },
];

export default restaurantList;
